### ISSUE TITLE
Can't Login!

### ISSUE THREAD

**Issue by Bilalkamal** [Teamial/DevTrack#1]
![Screenshot 2024-12-11 at 23 03 43](https://github.com/user-attachments/assets/6c89bed9-e50e-44c6-96d5-d1edb2fdc33a)

Tried DevTrack: Login to GitHub in the command palette and got this 👆

Any ideas?

**Comment by Teamial** [comment]
Just updated the extension so restart VS Code and see if that fix's it! Let me know if it works.

**Comment by Bilalkamal** [comment]
![Screenshot 2024-12-12 at 15 26 26](https://github.com/user-attachments/assets/08d18a08-4886-44eb-b757-7e9cf671eba2)
Yes, that worked. Thanks!
