### ISSUE TITLE
Git Login Error whenever I switch projects

### ISSUE THREAD

**Issue by kads1024** [Teamial/DevTrack#8]
![image](https://github.com/user-attachments/assets/b371023c-bdb2-4c5c-bf1e-0858b4e3ee81)

Replication Step:
1. Connect DevTrack To one project
2. Open Another Project and close the Old Project
3. Connect DevTrack to the New Project
4. Error Occurs

Note: DevTrack successfully connects to the old project and  Git configuration is setup properly

**Comment by Teamial** [comment]
Could you answer these questions for me?  1. What OS are you using? 
2. Are you getting any additional error details in the DevTrack Output panel? (You can view this by opening the Output panel in VS Code and selecting "DevTrack" from the dropdown)

3. When you say "Connect DevTrack to the New Project", could you clarify the exact steps you're taking? Are you:
Using "DevTrack: Start Tracking" command or using "DevTrack: Login to GitHub" command?
Or something else? Because DevTrack should connect on it's own, unless that's when the error occurs on it's own?

4. Does this happen only when switching between projects in different windows, or does it also occur if you:
Switch projects within the same VS Code window or close VS Code completely and reopen with the new project?

5. Are both projects using the same GitHub account, or are you trying to connect with different GitHub accounts?

6. After the error occurs, are you able to resolve it by:
Logging out and logging back in to GitHub?
Stopping and restarting tracking?
Or does it persist until you switch back to the original project?

**Comment by kads1024** [comment]
1. Windows
2. 
```
DevTrack: Extension activated.
DevTrack: Found Git in PATH at C:/Program Files/Git/cmd/git.exe
DevTrack: Using Git executable: C:/Program Files/Git/cmd/git.exe
DevTrack: Found Git in PATH at C:/Program Files/Git/cmd/git.exe
DevTrack: Successfully verified Git at: C:/Program Files/Git/cmd/git.exe
DevTrack: File system watcher initialized.
DevTrack: Loaded project context
DevTrack: Git configuration verified
DevTrack: Windows Git system configuration verified
DevTrack: Starting initialization...
DevTrack: Git found - git version 2.47.1.windows.1
DevTrack: Found Git in PATH at C:/Program Files/Git/cmd/git.exe
DevTrack: Successfully verified Git at: C:/Program Files/Git/cmd/git.exe
DevTrack: Git configuration verified
DevTrack: Windows Git system configuration verified
DevTrack: Operation failed (attempt 1/3): Pushing to https://github.com/kads1024/code-tracking.git
error: src refspec main does not match any
error: failed to push some refs to 'https://github.com/kads1024/code-tracking.git'

DevTrack: Operation failed (attempt 2/3): Pushing to https://github.com/kads1024/code-tracking.git
error: src refspec main does not match any
error: failed to push some refs to 'https://github.com/kads1024/code-tracking.git'

DevTrack: Operation failed (attempt 3/3): Pushing to https://github.com/kads1024/code-tracking.git
error: src refspec main does not match any
error: failed to push some refs to 'https://github.com/kads1024/code-tracking.git'

DevTrack: Git operation failed - Pushing to https://github.com/kads1024/code-tracking.git
error: src refspec main does not match any
error: failed to push some refs to 'https://github.com/kads1024/code-tracking.git'

DevTrack: Operation failed: Error: Pushing to https://github.com/kads1024/code-tracking.git
error: src refspec main does not match any
error: failed to push some refs to 'https://github.com/kads1024/code-tracking.git'

DevTrack: Initialization failed - There was an issue with Git configuration. Please ensure Git is properly installed and try again.
DevTrack: GitHub connection failed - There was an issue with Git configuration. Please ensure Git is properly installed and try again.
```

3. DevTrack: Login to GitHub

4. This happens when I close VS Code completely and reopen with the new project

5. Yes. Same Github Account

6. 
Logging out and logging back in to GitHub? Doesnt work
Stopping and restarting tracking? Doesnt allow me to restart tracking without login first
Or does it persist until you switch back to the original project? It persist on all projects opened moving forward, including reopening the original/old project

**Comment by Teamial** [comment]
I just released update v4.1.13, when you get the option to update DevTrack please do so and let me know if you're experiencing the same issue.

**Comment by kads1024** [comment]
```
evTrack: Extension activated.
DevTrack: Found Git in PATH at C:/Program Files/Git/cmd/git.exe
DevTrack: Using Git executable: C:/Program Files/Git/cmd/git.exe
DevTrack: Found Git in PATH at C:/Program Files/Git/cmd/git.exe
DevTrack: Successfully verified Git at: C:/Program Files/Git/cmd/git.exe
DevTrack: File system watcher initialized.
DevTrack: Loaded project context
DevTrack: Git configuration verified
DevTrack: Windows Git system configuration verified
DevTrack: Starting initialization...
DevTrack: Git found - git version 2.47.1.windows.1
DevTrack: Found Git in PATH at C:/Program Files/Git/cmd/git.exe
DevTrack: Successfully verified Git at: C:/Program Files/Git/cmd/git.exe
DevTrack: Git configuration verified
DevTrack: Windows Git system configuration verified
DevTrack: Operation failed (attempt 1/3): fatal: your current branch 'main' does not have any commits yet

DevTrack: Operation failed (attempt 2/3): fatal: your current branch 'main' does not have any commits yet

DevTrack: Operation failed (attempt 3/3): fatal: your current branch 'main' does not have any commits yet

DevTrack: Git operation failed - fatal: your current branch 'main' does not have any commits yet

DevTrack: Operation failed: Error: fatal: your current branch 'main' does not have any commits yet

DevTrack: Initialization failed - fatal: your current branch 'main' does not have any commits yet

DevTrack: GitHub connection failed - fatal: your current branch 'main' does not have any commits yet
```




I Just updated, and this is the new error

**Comment by kads1024** [comment]
Sorry. It works now, I just added a commit to my main branch. Thanks! Can close issue now
